defaults:
  - base

_target_: gflownet.envs.arithmetictree.ArithmeticBuilder

id: arithmetictree
max_operations: 5
min_int: 1
max_int:  4
operations: ['+', '*']
stock: [1, 2]
target: 4
allow_early_eos: False
buffer:
  data_path: null
  train: null
  test: null