defaults:
  - base

_target_: gflownet.envs.arithmetictree.ArithmeticBuilder

id: arithmetictree
max_operations: 1
min_int: 1
max_int:  4
opaerations: ['+', '*']
stock: [1, 2]
target: 4
buffer:
  data_path: null
  train: null
  test: null

