defaults:
  - base

_target_: gflownet.envs.arithmetictree.ArithmeticBuilder

id: arithmetictree
max_operations: 6
min_int: 1
max_int:  9
opaerations: ['+', '*']
stock: [1, 2]
target: 9
buffer:
  data_path: null
  train: null
  test: null

