defaults:
  - base

_target_: gflownet.envs.arithmetictree.ArithmeticBuilder

id: arithmetictree
max_operations: 6
min_int: -20
max_int:  20
opaerations: ['+', '*']
stock: [1, -1, 2, -2, 3, -3]
target: 0
buffer:
  data_path: null
  train: null
  test: null

