defaults:
  - base

_target_: gflownet.envs.arithmetictree.ArithmeticBuilder

id: arithmetictree
max_operations: 4
min_int: 2
max_int:  20
operations: ['+', '*']
stock: [2, 3]
targets: [15, 16, 18, 19]
allow_early_eos: False
buffer:
  data_path: null
  train: 
    type: random
    n: 50
    output_pkl: arithmetictree_train.pkl
  test:
    type: random
    n: 50
    output_csv: arithmetictree_test.csv
    output_pkl: arithmetictree_test.pkl
