defaults:
  - base

_target_: gflownet.envs.reactiontree.ReactionTreeBuilder

id: reactiontree
# template_file: external/reactiontree_data/uspto_unique_templates_filtered.csv
# stock_file: data/reactiontree/zinc_stock.hdf5
target_file: external/reactiontree_data/targets_20.txt
max_reactions: 6
buffer:
  data_path: null
  train: null
  test: 
    type: random
    output_csv: reactiontree_test.csv
    output_pkl: reactiontree_test.pkl