defaults:
  - base

_target_: gflownet.envs.reactiontree.ReactionTreeBuilder

id: reactiontree
template_file: data/reactiontree/uspto_unique_templates_filtered.csv
# stock_file: data/reactiontree/zinc_stock.hdf5
target_smiles: Cc1cccc(c1N(CC(=O)Nc2ccc(cc2)c3ncon3)C(=O)C4CCS(=O)(=O)CC4)C
max_reactions: 3
buffer:
  data_path: null
  train: null
  test: 
    type: random
    output_csv: reactiontree_test.csv
    output_pkl: reactiontree_test.pkl