defaults:
  - base

_target_: gflownet.envs.reactiontree.ReactionTreeBuilder

id: reactiontree
template_file: data/reactiontree/uspto_unique_templates_filtered.csv
# stock_file: data/reactiontree/zinc_stock.hdf5
target_smiles: COc1ncc(-c2cc3c(c(OCCN4CCC(C(C)(C)O)CC4)c2)COC3)cc1NS(C)(=O)=O
max_reactions: 3
buffer:
  data_path: null
  train: null
  test: 
    type: random
    output_csv: reactiontree_test.csv
    output_pkl: reactiontree_test.pkl