defaults:
  - base

_target_: gflownet.envs.reactiontree.ReactionTreeBuilder

id: reactiontree
template_file: data/reactiontree/uspto_unique_templates_filtered.csv
# stock_file: data/reactiontree/zinc_stock.hdf5
target_smiles: O=C(O)c1ccccc1Nc1cccc(C(F)(F)F)c1-c1ccccc1
max_reactions: 6
buffer:
  data_path: null
  train: null
  test: 
    type: random
    output_csv: reactiontree_test.csv
    output_pkl: reactiontree_test.pkl